/**
 * Static lookup table of WC3 creep unit stats.
 * Covers creeps appearing on competitive maps.
 * Source: WC3 game data / community wiki.
 */

export interface CreepStats {
  name: string;
  level: number;
  hp: number;
  mana: number;
  armor: number;
  armorType: "light" | "medium" | "heavy" | "fortified" | "hero" | "unarmored" | "divine";
  damageMin: number;
  damageMax: number;
  attackType: "normal" | "pierce" | "siege" | "magic" | "chaos" | "hero" | "spells";
  xpBounty: number;
  goldBounty: number;
  abilities: string[];
  tags: string[];
}

export const CREEP_DATA: Record<string, CreepStats> = {
  // Forest Trolls
  nftr: {
    name: "Forest Troll",
    level: 2,
    hp: 240,
    mana: 0,
    armor: 0,
    armorType: "medium",
    damageMin: 11,
    damageMax: 13,
    attackType: "normal",
    xpBounty: 40,
    goldBounty: 16,
    abilities: [],
    tags: ["troll"],
  },
  nftt: {
    name: "Forest Troll Trapper",
    level: 3,
    hp: 300,
    mana: 200,
    armor: 0,
    armorType: "medium",
    damageMin: 17,
    damageMax: 18,
    attackType: "pierce",
    xpBounty: 60,
    goldBounty: 22,
    abilities: ["ensnare"],
    tags: ["troll"],
  },
  nftb: {
    name: "Forest Troll Berserker",
    level: 4,
    hp: 450,
    mana: 0,
    armor: 1,
    armorType: "medium",
    damageMin: 21,
    damageMax: 24,
    attackType: "normal",
    xpBounty: 80,
    goldBounty: 30,
    abilities: ["berserk"],
    tags: ["troll"],
  },
  nftk: {
    name: "Forest Troll High Priest",
    level: 5,
    hp: 540,
    mana: 400,
    armor: 0,
    armorType: "light",
    damageMin: 23,
    damageMax: 28,
    attackType: "magic",
    xpBounty: 100,
    goldBounty: 39,
    abilities: ["heal", "inner_fire"],
    tags: ["troll", "caster"],
  },

  // Gnolls
  ngno: {
    name: "Gnoll",
    level: 1,
    hp: 180,
    mana: 0,
    armor: 0,
    armorType: "light",
    damageMin: 9,
    damageMax: 10,
    attackType: "normal",
    xpBounty: 25,
    goldBounty: 10,
    abilities: [],
    tags: ["gnoll"],
  },
  ngnw: {
    name: "Gnoll Warden",
    level: 3,
    hp: 350,
    mana: 200,
    armor: 0,
    armorType: "medium",
    damageMin: 16,
    damageMax: 19,
    attackType: "normal",
    xpBounty: 60,
    goldBounty: 22,
    abilities: ["purge"],
    tags: ["gnoll", "caster"],
  },
  ngnb: {
    name: "Gnoll Brute",
    level: 4,
    hp: 490,
    mana: 0,
    armor: 2,
    armorType: "heavy",
    damageMin: 24,
    damageMax: 28,
    attackType: "normal",
    xpBounty: 80,
    goldBounty: 31,
    abilities: [],
    tags: ["gnoll"],
  },

  // Kobolds
  nkob: {
    name: "Kobold",
    level: 1,
    hp: 160,
    mana: 0,
    armor: 0,
    armorType: "light",
    damageMin: 7,
    damageMax: 8,
    attackType: "normal",
    xpBounty: 25,
    goldBounty: 10,
    abilities: [],
    tags: ["kobold"],
  },
  nkog: {
    name: "Kobold Geomancer",
    level: 2,
    hp: 240,
    mana: 200,
    armor: 0,
    armorType: "light",
    damageMin: 12,
    damageMax: 14,
    attackType: "magic",
    xpBounty: 40,
    goldBounty: 18,
    abilities: ["slow"],
    tags: ["kobold", "caster"],
  },
  nkol: {
    name: "Kobold Tunneler",
    level: 3,
    hp: 340,
    mana: 0,
    armor: 1,
    armorType: "medium",
    damageMin: 18,
    damageMax: 21,
    attackType: "normal",
    xpBounty: 60,
    goldBounty: 23,
    abilities: [],
    tags: ["kobold"],
  },

  // Ogres
  nogr: {
    name: "Ogre Warrior",
    level: 4,
    hp: 525,
    mana: 0,
    armor: 2,
    armorType: "heavy",
    damageMin: 21,
    damageMax: 25,
    attackType: "normal",
    xpBounty: 80,
    goldBounty: 30,
    abilities: [],
    tags: ["ogre"],
  },
  nogm: {
    name: "Ogre Mauler",
    level: 5,
    hp: 700,
    mana: 0,
    armor: 3,
    armorType: "heavy",
    damageMin: 29,
    damageMax: 35,
    attackType: "normal",
    xpBounty: 100,
    goldBounty: 40,
    abilities: [],
    tags: ["ogre"],
  },
  nogl: {
    name: "Ogre Lord",
    level: 6,
    hp: 850,
    mana: 300,
    armor: 3,
    armorType: "heavy",
    damageMin: 33,
    damageMax: 40,
    attackType: "normal",
    xpBounty: 120,
    goldBounty: 49,
    abilities: ["war_stomp"],
    tags: ["ogre"],
  },

  // Murlocs
  nmrl: {
    name: "Murloc Tiderunner",
    level: 1,
    hp: 150,
    mana: 0,
    armor: 0,
    armorType: "light",
    damageMin: 7,
    damageMax: 8,
    attackType: "normal",
    xpBounty: 25,
    goldBounty: 10,
    abilities: [],
    tags: ["murloc"],
  },
  nmrr: {
    name: "Murloc Huntsman",
    level: 3,
    hp: 300,
    mana: 0,
    armor: 0,
    armorType: "medium",
    damageMin: 14,
    damageMax: 16,
    attackType: "pierce",
    xpBounty: 60,
    goldBounty: 22,
    abilities: ["ensnare"],
    tags: ["murloc"],
  },
  nmrm: {
    name: "Murloc Nightcrawler",
    level: 4,
    hp: 450,
    mana: 200,
    armor: 1,
    armorType: "medium",
    damageMin: 22,
    damageMax: 26,
    attackType: "normal",
    xpBounty: 80,
    goldBounty: 30,
    abilities: [],
    tags: ["murloc"],
  },

  // Elementals
  nele: {
    name: "Enraged Elemental",
    level: 2,
    hp: 300,
    mana: 0,
    armor: 1,
    armorType: "heavy",
    damageMin: 14,
    damageMax: 16,
    attackType: "normal",
    xpBounty: 40,
    goldBounty: 17,
    abilities: [],
    tags: ["elemental"],
  },

  // Golems
  ngst: {
    name: "Granite Golem",
    level: 5,
    hp: 675,
    mana: 0,
    armor: 4,
    armorType: "fortified",
    damageMin: 30,
    damageMax: 36,
    attackType: "normal",
    xpBounty: 100,
    goldBounty: 41,
    abilities: ["hardened_skin"],
    tags: ["golem"],
  },

  // Hydras
  nhyh: {
    name: "Hydra Hatchling",
    level: 4,
    hp: 475,
    mana: 0,
    armor: 1,
    armorType: "heavy",
    damageMin: 20,
    damageMax: 24,
    attackType: "normal",
    xpBounty: 80,
    goldBounty: 30,
    abilities: [],
    tags: ["hydra"],
  },

  // Neutral bosses & misc
  ntrt: {
    name: "Thornby",
    level: 5,
    hp: 600,
    mana: 300,
    armor: 2,
    armorType: "heavy",
    damageMin: 26,
    damageMax: 32,
    attackType: "normal",
    xpBounty: 100,
    goldBounty: 40,
    abilities: ["thorns_aura"],
    tags: ["treant"],
  },

  ntrg: {
    name: "Treant",
    level: 7,
    hp: 1100,
    mana: 400,
    armor: 4,
    armorType: "heavy",
    damageMin: 38,
    damageMax: 46,
    attackType: "normal",
    xpBounty: 155,
    goldBounty: 60,
    abilities: ["entangle"],
    tags: ["treant"],
  },

  nltc: {
    name: "Lightning Lizard",
    level: 3,
    hp: 340,
    mana: 300,
    armor: 0,
    armorType: "medium",
    damageMin: 15,
    damageMax: 18,
    attackType: "pierce",
    xpBounty: 60,
    goldBounty: 22,
    abilities: ["purge"],
    tags: ["lizard"],
  },

  // Enforcers
  nenf: {
    name: "Enforcer",
    level: 4,
    hp: 475,
    mana: 200,
    armor: 2,
    armorType: "medium",
    damageMin: 22,
    damageMax: 26,
    attackType: "normal",
    xpBounty: 80,
    goldBounty: 30,
    abilities: [],
    tags: ["enforcer"],
  },

  // Wizards
  nwiz: {
    name: "Rogue Wizard",
    level: 3,
    hp: 280,
    mana: 300,
    armor: 0,
    armorType: "light",
    damageMin: 15,
    damageMax: 18,
    attackType: "magic",
    xpBounty: 60,
    goldBounty: 23,
    abilities: ["fireball"],
    tags: ["wizard", "caster"],
  },

  // Void Walkers
  nvdw: {
    name: "Voidwalker",
    level: 3,
    hp: 300,
    mana: 200,
    armor: 1,
    armorType: "medium",
    damageMin: 16,
    damageMax: 19,
    attackType: "magic",
    xpBounty: 60,
    goldBounty: 23,
    abilities: ["mana_burn"],
    tags: ["void"],
  },

  // Spiders
  nsph: {
    name: "Spider",
    level: 1,
    hp: 160,
    mana: 0,
    armor: 0,
    armorType: "light",
    damageMin: 8,
    damageMax: 9,
    attackType: "normal",
    xpBounty: 25,
    goldBounty: 10,
    abilities: [],
    tags: ["spider"],
  },
  nspb: {
    name: "Spitting Spider",
    level: 2,
    hp: 250,
    mana: 0,
    armor: 0,
    armorType: "medium",
    damageMin: 13,
    damageMax: 15,
    attackType: "pierce",
    xpBounty: 40,
    goldBounty: 17,
    abilities: [],
    tags: ["spider"],
  },
  nspc: {
    name: "Spider Crab",
    level: 3,
    hp: 350,
    mana: 0,
    armor: 2,
    armorType: "heavy",
    damageMin: 17,
    damageMax: 20,
    attackType: "normal",
    xpBounty: 60,
    goldBounty: 22,
    abilities: [],
    tags: ["spider"],
  },

  // Satyrs
  nsat: {
    name: "Satyr",
    level: 2,
    hp: 240,
    mana: 200,
    armor: 0,
    armorType: "light",
    damageMin: 12,
    damageMax: 14,
    attackType: "magic",
    xpBounty: 40,
    goldBounty: 16,
    abilities: [],
    tags: ["satyr"],
  },

  // Skeletons
  nske: {
    name: "Skeletal Warrior",
    level: 1,
    hp: 180,
    mana: 0,
    armor: 1,
    armorType: "medium",
    damageMin: 9,
    damageMax: 10,
    attackType: "normal",
    xpBounty: 25,
    goldBounty: 10,
    abilities: [],
    tags: ["undead"],
  },

  // Wolves
  nwlg: {
    name: "Giant Wolf",
    level: 2,
    hp: 250,
    mana: 0,
    armor: 0,
    armorType: "medium",
    damageMin: 13,
    damageMax: 14,
    attackType: "normal",
    xpBounty: 40,
    goldBounty: 16,
    abilities: [],
    tags: ["wolf"],
  },
  nwlt: {
    name: "Timber Wolf",
    level: 1,
    hp: 160,
    mana: 0,
    armor: 0,
    armorType: "light",
    damageMin: 8,
    damageMax: 9,
    attackType: "normal",
    xpBounty: 25,
    goldBounty: 10,
    abilities: [],
    tags: ["wolf"],
  },

  // Golems (rock)
  nrog: {
    name: "Rock Golem",
    level: 4,
    hp: 550,
    mana: 0,
    armor: 3,
    armorType: "fortified",
    damageMin: 24,
    damageMax: 29,
    attackType: "normal",
    xpBounty: 80,
    goldBounty: 31,
    abilities: ["hardened_skin"],
    tags: ["golem"],
  },

  // Centaurs
  ncer: {
    name: "Centaur Outrunner",
    level: 2,
    hp: 250,
    mana: 0,
    armor: 1,
    armorType: "medium",
    damageMin: 13,
    damageMax: 14,
    attackType: "normal",
    xpBounty: 40,
    goldBounty: 16,
    abilities: [],
    tags: ["centaur"],
  },

  // Makrura (lobster)
  nmsc: {
    name: "Makrura Snapper",
    level: 2,
    hp: 260,
    mana: 0,
    armor: 1,
    armorType: "heavy",
    damageMin: 12,
    damageMax: 14,
    attackType: "normal",
    xpBounty: 40,
    goldBounty: 17,
    abilities: [],
    tags: ["makrura"],
  },

  // Quillbeasts
  nsqt: {
    name: "Quillboar",
    level: 4,
    hp: 475,
    mana: 0,
    armor: 1,
    armorType: "medium",
    damageMin: 21,
    damageMax: 25,
    attackType: "normal",
    xpBounty: 80,
    goldBounty: 30,
    abilities: ["quill_spray"],
    tags: ["quillboar"],
  },

  // Misc neutral heroes/boss units (creep versions)
  nrel: {
    name: "Reef Elemental",
    level: 3,
    hp: 350,
    mana: 0,
    armor: 2,
    armorType: "heavy",
    damageMin: 17,
    damageMax: 20,
    attackType: "normal",
    xpBounty: 60,
    goldBounty: 22,
    abilities: [],
    tags: ["elemental"],
  },
  nlsn: {
    name: "Siren",
    level: 4,
    hp: 475,
    mana: 400,
    armor: 1,
    armorType: "light",
    damageMin: 22,
    damageMax: 26,
    attackType: "magic",
    xpBounty: 80,
    goldBounty: 31,
    abilities: ["curse", "slow"],
    tags: ["naga", "caster"],
  },

  // Gnoll overseer
  ngme: {
    name: "Gnoll Overseer",
    level: 2,
    hp: 260,
    mana: 0,
    armor: 1,
    armorType: "medium",
    damageMin: 12,
    damageMax: 14,
    attackType: "normal",
    xpBounty: 40,
    goldBounty: 16,
    abilities: ["command_aura"],
    tags: ["gnoll"],
  },

  // Pig
  npig: {
    name: "Pig",
    level: 1,
    hp: 50,
    mana: 0,
    armor: 0,
    armorType: "unarmored",
    damageMin: 1,
    damageMax: 1,
    attackType: "normal",
    xpBounty: 12,
    goldBounty: 5,
    abilities: [],
    tags: ["critter"],
  },

  // Sheep/critters
  nshe: {
    name: "Sheep",
    level: 1,
    hp: 12,
    mana: 0,
    armor: 0,
    armorType: "unarmored",
    damageMin: 0,
    damageMax: 0,
    attackType: "normal",
    xpBounty: 0,
    goldBounty: 0,
    abilities: [],
    tags: ["critter"],
  },

  // Dark Troll
  ndtr: {
    name: "Dark Troll",
    level: 3,
    hp: 340,
    mana: 0,
    armor: 1,
    armorType: "medium",
    damageMin: 17,
    damageMax: 20,
    attackType: "normal",
    xpBounty: 60,
    goldBounty: 23,
    abilities: [],
    tags: ["troll"],
  },
  ndtb: {
    name: "Dark Troll Berserker",
    level: 4,
    hp: 475,
    mana: 0,
    armor: 1,
    armorType: "medium",
    damageMin: 22,
    damageMax: 26,
    attackType: "normal",
    xpBounty: 80,
    goldBounty: 31,
    abilities: [],
    tags: ["troll"],
  },
  ndth: {
    name: "Dark Troll Shadow Priest",
    level: 4,
    hp: 350,
    mana: 400,
    armor: 0,
    armorType: "light",
    damageMin: 19,
    damageMax: 23,
    attackType: "magic",
    xpBounty: 80,
    goldBounty: 30,
    abilities: ["heal", "abolish_magic"],
    tags: ["troll", "caster"],
  },

  // Furbolgs
  nfrb: {
    name: "Furbolg",
    level: 3,
    hp: 400,
    mana: 0,
    armor: 2,
    armorType: "heavy",
    damageMin: 17,
    damageMax: 20,
    attackType: "normal",
    xpBounty: 60,
    goldBounty: 23,
    abilities: [],
    tags: ["furbolg"],
  },
  nfrg: {
    name: "Furbolg Tracker",
    level: 4,
    hp: 550,
    mana: 0,
    armor: 2,
    armorType: "heavy",
    damageMin: 23,
    damageMax: 27,
    attackType: "normal",
    xpBounty: 80,
    goldBounty: 31,
    abilities: [],
    tags: ["furbolg"],
  },

  // Bandit
  nban: {
    name: "Bandit",
    level: 2,
    hp: 240,
    mana: 0,
    armor: 1,
    armorType: "medium",
    damageMin: 12,
    damageMax: 13,
    attackType: "normal",
    xpBounty: 40,
    goldBounty: 17,
    abilities: [],
    tags: ["bandit"],
  },
  nbrg: {
    name: "Brigand",
    level: 3,
    hp: 340,
    mana: 0,
    armor: 1,
    armorType: "medium",
    damageMin: 17,
    damageMax: 19,
    attackType: "normal",
    xpBounty: 60,
    goldBounty: 23,
    abilities: [],
    tags: ["bandit"],
  },

  // Skeletal Archers
  nskl: {
    name: "Skeletal Archer",
    level: 2,
    hp: 200,
    mana: 0,
    armor: 0,
    armorType: "medium",
    damageMin: 12,
    damageMax: 14,
    attackType: "pierce",
    xpBounty: 40,
    goldBounty: 16,
    abilities: [],
    tags: ["undead"],
  },
  nubr: {
    name: "Skeletal Marksman",
    level: 3,
    hp: 300,
    mana: 0,
    armor: 0,
    armorType: "medium",
    damageMin: 18,
    damageMax: 20,
    attackType: "pierce",
    xpBounty: 60,
    goldBounty: 22,
    abilities: [],
    tags: ["undead"],
  },

  // Harpy
  nhar: {
    name: "Harpy",
    level: 2,
    hp: 210,
    mana: 0,
    armor: 0,
    armorType: "light",
    damageMin: 11,
    damageMax: 13,
    attackType: "normal",
    xpBounty: 40,
    goldBounty: 16,
    abilities: [],
    tags: ["harpy"],
  },
  nhhr: {
    name: "Harpy Rogue",
    level: 3,
    hp: 310,
    mana: 200,
    armor: 0,
    armorType: "light",
    damageMin: 16,
    damageMax: 19,
    attackType: "normal",
    xpBounty: 60,
    goldBounty: 23,
    abilities: ["faerie_fire"],
    tags: ["harpy"],
  },

  // Sea creatures
  nsqo: {
    name: "Sea Giant",
    level: 6,
    hp: 900,
    mana: 0,
    armor: 3,
    armorType: "heavy",
    damageMin: 31,
    damageMax: 38,
    attackType: "normal",
    xpBounty: 120,
    goldBounty: 49,
    abilities: ["war_stomp"],
    tags: ["giant"],
  },

  // Tuskaar
  ntka: {
    name: "Tuskarr",
    level: 2,
    hp: 240,
    mana: 0,
    armor: 0,
    armorType: "medium",
    damageMin: 12,
    damageMax: 13,
    attackType: "normal",
    xpBounty: 40,
    goldBounty: 16,
    abilities: [],
    tags: ["tuskarr"],
  },
  ntkf: {
    name: "Tuskarr Fighter",
    level: 3,
    hp: 340,
    mana: 0,
    armor: 1,
    armorType: "medium",
    damageMin: 17,
    damageMax: 20,
    attackType: "normal",
    xpBounty: 60,
    goldBounty: 23,
    abilities: [],
    tags: ["tuskarr"],
  },
  ntkw: {
    name: "Tuskarr Warrior",
    level: 5,
    hp: 600,
    mana: 0,
    armor: 2,
    armorType: "heavy",
    damageMin: 27,
    damageMax: 33,
    attackType: "normal",
    xpBounty: 100,
    goldBounty: 40,
    abilities: [],
    tags: ["tuskarr"],
  },

  // Dragon Spawn
  nrdk: {
    name: "Red Drake",
    level: 5,
    hp: 600,
    mana: 0,
    armor: 2,
    armorType: "heavy",
    damageMin: 26,
    damageMax: 33,
    attackType: "normal",
    xpBounty: 100,
    goldBounty: 40,
    abilities: ["devour"],
    tags: ["dragon"],
  },
  nrdl: {
    name: "Red Dragon Whelp",
    level: 3,
    hp: 300,
    mana: 0,
    armor: 1,
    armorType: "medium",
    damageMin: 16,
    damageMax: 19,
    attackType: "normal",
    xpBounty: 60,
    goldBounty: 22,
    abilities: [],
    tags: ["dragon"],
  },

  // Nerubian
  nnht: {
    name: "Nerubian Warrior",
    level: 3,
    hp: 340,
    mana: 0,
    armor: 2,
    armorType: "heavy",
    damageMin: 16,
    damageMax: 19,
    attackType: "normal",
    xpBounty: 60,
    goldBounty: 22,
    abilities: [],
    tags: ["nerubian"],
  },
  nnsg: {
    name: "Nerubian Seer",
    level: 4,
    hp: 400,
    mana: 300,
    armor: 1,
    armorType: "light",
    damageMin: 20,
    damageMax: 24,
    attackType: "magic",
    xpBounty: 80,
    goldBounty: 31,
    abilities: ["frost_armor"],
    tags: ["nerubian", "caster"],
  },
  nnsu: {
    name: "Nerubian Spider Lord",
    level: 6,
    hp: 800,
    mana: 400,
    armor: 3,
    armorType: "heavy",
    damageMin: 33,
    damageMax: 40,
    attackType: "normal",
    xpBounty: 120,
    goldBounty: 48,
    abilities: ["web"],
    tags: ["nerubian"],
  },

  // Ice Trolls
  nits: {
    name: "Ice Troll",
    level: 3,
    hp: 300,
    mana: 0,
    armor: 0,
    armorType: "medium",
    damageMin: 16,
    damageMax: 18,
    attackType: "pierce",
    xpBounty: 60,
    goldBounty: 22,
    abilities: [],
    tags: ["troll"],
  },
  nitp: {
    name: "Ice Troll Priest",
    level: 4,
    hp: 400,
    mana: 400,
    armor: 0,
    armorType: "light",
    damageMin: 19,
    damageMax: 23,
    attackType: "magic",
    xpBounty: 80,
    goldBounty: 31,
    abilities: ["heal", "inner_fire"],
    tags: ["troll", "caster"],
  },
  nitb: {
    name: "Ice Troll Berserker",
    level: 5,
    hp: 550,
    mana: 0,
    armor: 1,
    armorType: "medium",
    damageMin: 27,
    damageMax: 32,
    attackType: "normal",
    xpBounty: 100,
    goldBounty: 39,
    abilities: ["berserk"],
    tags: ["troll"],
  },

  // Sasquatch
  nstl: {
    name: "Sasquatch",
    level: 4,
    hp: 500,
    mana: 0,
    armor: 2,
    armorType: "heavy",
    damageMin: 22,
    damageMax: 26,
    attackType: "normal",
    xpBounty: 80,
    goldBounty: 30,
    abilities: [],
    tags: ["sasquatch"],
  },
  nsth: {
    name: "Sasquatch Oracle",
    level: 5,
    hp: 600,
    mana: 400,
    armor: 2,
    armorType: "heavy",
    damageMin: 27,
    damageMax: 33,
    attackType: "normal",
    xpBounty: 100,
    goldBounty: 40,
    abilities: ["rejuvenation"],
    tags: ["sasquatch", "caster"],
  },

  // Thunder Lizard
  nthl: {
    name: "Thunder Lizard",
    level: 6,
    hp: 850,
    mana: 400,
    armor: 3,
    armorType: "heavy",
    damageMin: 33,
    damageMax: 40,
    attackType: "normal",
    xpBounty: 120,
    goldBounty: 49,
    abilities: ["war_stomp"],
    tags: ["lizard"],
  },

  // Wildkin
  nowb: {
    name: "Wildkin",
    level: 3,
    hp: 350,
    mana: 0,
    armor: 1,
    armorType: "heavy",
    damageMin: 17,
    damageMax: 20,
    attackType: "normal",
    xpBounty: 60,
    goldBounty: 22,
    abilities: [],
    tags: ["wildkin"],
  },
  now3: {
    name: "Enraged Wildkin",
    level: 5,
    hp: 600,
    mana: 0,
    armor: 3,
    armorType: "heavy",
    damageMin: 28,
    damageMax: 34,
    attackType: "normal",
    xpBounty: 100,
    goldBounty: 40,
    abilities: [],
    tags: ["wildkin"],
  },

  // Green dragon
  ngrk: {
    name: "Green Dragon Whelp",
    level: 3,
    hp: 340,
    mana: 200,
    armor: 1,
    armorType: "medium",
    damageMin: 16,
    damageMax: 19,
    attackType: "magic",
    xpBounty: 60,
    goldBounty: 23,
    abilities: [],
    tags: ["dragon"],
  },

  // Fallen Priests
  ndmu: {
    name: "Dalaran Mutant",
    level: 3,
    hp: 320,
    mana: 200,
    armor: 0,
    armorType: "medium",
    damageMin: 15,
    damageMax: 18,
    attackType: "normal",
    xpBounty: 60,
    goldBounty: 22,
    abilities: [],
    tags: ["dalaran"],
  },

  // Skeleton Archer variant
  nska: {
    name: "Skeleton Archer",
    level: 1,
    hp: 180,
    mana: 0,
    armor: 0,
    armorType: "heavy",
    damageMin: 13,
    damageMax: 15,
    attackType: "pierce",
    xpBounty: 25,
    goldBounty: 5,
    abilities: [],
    tags: ["undead"],
  },
  nskg: {
    name: "Giant Skeleton Warrior",
    level: 3,
    hp: 380,
    mana: 0,
    armor: 4,
    armorType: "heavy",
    damageMin: 12,
    damageMax: 18,
    attackType: "normal",
    xpBounty: 60,
    goldBounty: 18,
    abilities: [],
    tags: ["undead"],
  },
  nsko: {
    name: "Skeletal Orc",
    level: 3,
    hp: 375,
    mana: 0,
    armor: 2,
    armorType: "heavy",
    damageMin: 14,
    damageMax: 15,
    attackType: "normal",
    xpBounty: 60,
    goldBounty: 18,
    abilities: [],
    tags: ["undead"],
  },

  // Forest Troll variants
  nfsh: {
    name: "Forest Troll High Priest",
    level: 4,
    hp: 450,
    mana: 300,
    armor: 0,
    armorType: "medium",
    damageMin: 17,
    damageMax: 21,
    attackType: "pierce",
    xpBounty: 80,
    goldBounty: 28,
    abilities: ["heal", "abolish_magic", "inner_fire"],
    tags: ["troll", "caster"],
  },
  nfsp: {
    name: "Forest Troll Shadow Priest",
    level: 2,
    hp: 240,
    mana: 200,
    armor: 0,
    armorType: "heavy",
    damageMin: 17,
    damageMax: 24,
    attackType: "magic",
    xpBounty: 40,
    goldBounty: 14,
    abilities: ["heal", "abolish_magic"],
    tags: ["troll", "caster"],
  },

  // Dark Troll variants
  ndtt: {
    name: "Dark Troll Trapper",
    level: 3,
    hp: 340,
    mana: 0,
    armor: 1,
    armorType: "medium",
    damageMin: 21,
    damageMax: 29,
    attackType: "pierce",
    xpBounty: 60,
    goldBounty: 20,
    abilities: ["ensnare"],
    tags: ["troll"],
  },

  // Ice Troll variants
  nitr: {
    name: "Ice Troll",
    level: 2,
    hp: 300,
    mana: 0,
    armor: 0,
    armorType: "heavy",
    damageMin: 17,
    damageMax: 20,
    attackType: "pierce",
    xpBounty: 40,
    goldBounty: 14,
    abilities: [],
    tags: ["troll"],
  },
  nitw: {
    name: "Ice Troll Warlord",
    level: 6,
    hp: 750,
    mana: 0,
    armor: 0,
    armorType: "heavy",
    damageMin: 36,
    damageMax: 43,
    attackType: "pierce",
    xpBounty: 120,
    goldBounty: 44,
    abilities: ["trueshot_aura"],
    tags: ["troll"],
  },
  nitt: {
    name: "Ice Troll Trapper",
    level: 3,
    hp: 400,
    mana: 0,
    armor: 1,
    armorType: "medium",
    damageMin: 21,
    damageMax: 25,
    attackType: "pierce",
    xpBounty: 60,
    goldBounty: 20,
    abilities: ["ensnare"],
    tags: ["troll"],
  },
  nith: {
    name: "Ice Troll High Priest",
    level: 4,
    hp: 450,
    mana: 300,
    armor: 0,
    armorType: "medium",
    damageMin: 17,
    damageMax: 21,
    attackType: "magic",
    xpBounty: 80,
    goldBounty: 28,
    abilities: ["heal", "abolish_magic", "frost_armor"],
    tags: ["troll", "caster"],
  },

  // Gnoll variants
  ngns: {
    name: "Gnoll Assassin",
    level: 3,
    hp: 320,
    mana: 0,
    armor: 1,
    armorType: "medium",
    damageMin: 21,
    damageMax: 29,
    attackType: "pierce",
    xpBounty: 60,
    goldBounty: 20,
    abilities: [],
    tags: ["gnoll"],
  },
  ngnv: {
    name: "Gnoll Overseer",
    level: 5,
    hp: 750,
    mana: 0,
    armor: 3,
    armorType: "heavy",
    damageMin: 24,
    damageMax: 27,
    attackType: "normal",
    xpBounty: 100,
    goldBounty: 38,
    abilities: ["command_aura"],
    tags: ["gnoll"],
  },
  ngna: {
    name: "Gnoll Poacher",
    level: 1,
    hp: 240,
    mana: 0,
    armor: 0,
    armorType: "heavy",
    damageMin: 13,
    damageMax: 15,
    attackType: "pierce",
    xpBounty: 25,
    goldBounty: 5,
    abilities: [],
    tags: ["gnoll"],
  },

  // Ogre Magi
  nomg: {
    name: "Ogre Magi",
    level: 5,
    hp: 600,
    mana: 400,
    armor: 1,
    armorType: "heavy",
    damageMin: 24,
    damageMax: 27,
    attackType: "normal",
    xpBounty: 100,
    goldBounty: 38,
    abilities: ["bloodlust"],
    tags: ["ogre", "caster"],
  },

  // Magnataur
  nmgr: {
    name: "Magnataur Reaver",
    level: 8,
    hp: 1500,
    mana: 350,
    armor: 2,
    armorType: "heavy",
    damageMin: 54,
    damageMax: 61,
    attackType: "chaos",
    xpBounty: 200,
    goldBounty: 76,
    abilities: ["frost_bolt", "spell_immunity"],
    tags: ["magnataur"],
  },

  // Furbolg variants
  nfrl: {
    name: "Furbolg Champion",
    level: 4,
    hp: 550,
    mana: 0,
    armor: 2,
    armorType: "heavy",
    damageMin: 18,
    damageMax: 21,
    attackType: "normal",
    xpBounty: 80,
    goldBounty: 28,
    abilities: [],
    tags: ["furbolg"],
  },
  nfre: {
    name: "Furbolg Elder Shaman",
    level: 7,
    hp: 950,
    mana: 500,
    armor: 3,
    armorType: "heavy",
    damageMin: 41,
    damageMax: 52,
    attackType: "chaos",
    xpBounty: 155,
    goldBounty: 60,
    abilities: ["rejuvenation", "lightning_shield"],
    tags: ["furbolg", "caster"],
  },
  nfrs: {
    name: "Furbolg Shaman",
    level: 4,
    hp: 550,
    mana: 300,
    armor: 0,
    armorType: "medium",
    damageMin: 25,
    damageMax: 32,
    attackType: "pierce",
    xpBounty: 80,
    goldBounty: 28,
    abilities: ["rejuvenation"],
    tags: ["furbolg", "caster"],
  },

  // Wolves
  nwwd: {
    name: "Dire Frost Wolf",
    level: 6,
    hp: 750,
    mana: 400,
    armor: 2,
    armorType: "heavy",
    damageMin: 29,
    damageMax: 33,
    attackType: "normal",
    xpBounty: 120,
    goldBounty: 48,
    abilities: ["critical_strike", "roar"],
    tags: ["wolf"],
  },
  nwwf: {
    name: "Forest Wolf",
    level: 2,
    hp: 300,
    mana: 0,
    armor: 0,
    armorType: "heavy",
    damageMin: 12,
    damageMax: 13,
    attackType: "normal",
    xpBounty: 40,
    goldBounty: 14,
    abilities: ["critical_strike"],
    tags: ["wolf"],
  },

  // Wizards
  nwzr: {
    name: "Rogue Wizard",
    level: 3,
    hp: 340,
    mana: 300,
    armor: 0,
    armorType: "medium",
    damageMin: 23,
    damageMax: 27,
    attackType: "pierce",
    xpBounty: 60,
    goldBounty: 20,
    abilities: ["frost_armor"],
    tags: ["wizard", "caster"],
  },
  nwzg: {
    name: "Renegade Wizard",
    level: 5,
    hp: 600,
    mana: 400,
    armor: 0,
    armorType: "medium",
    damageMin: 30,
    damageMax: 39,
    attackType: "pierce",
    xpBounty: 100,
    goldBounty: 38,
    abilities: ["purge", "lightning_shield"],
    tags: ["wizard", "caster"],
  },

  // Mur'gul
  nmsn: {
    name: "Mur'gul Snarecaster",
    level: 4,
    hp: 375,
    mana: 300,
    armor: 2,
    armorType: "medium",
    damageMin: 28,
    damageMax: 37,
    attackType: "pierce",
    xpBounty: 80,
    goldBounty: 28,
    abilities: ["slow", "abolish_magic"],
    tags: ["murgul", "caster"],
  },
  nmbg: {
    name: "Mur'gul Blood-Gill",
    level: 2,
    hp: 300,
    mana: 200,
    armor: 2,
    armorType: "medium",
    damageMin: 17,
    damageMax: 20,
    attackType: "pierce",
    xpBounty: 40,
    goldBounty: 14,
    abilities: ["heal"],
    tags: ["murgul", "caster"],
  },
  nmtw: {
    name: "Mur'gul Tidewarrior",
    level: 3,
    hp: 400,
    mana: 0,
    armor: 1,
    armorType: "heavy",
    damageMin: 14,
    damageMax: 15,
    attackType: "normal",
    xpBounty: 60,
    goldBounty: 18,
    abilities: [],
    tags: ["murgul"],
  },
  nmrv: {
    name: "Mur'gul Marauder",
    level: 6,
    hp: 1000,
    mana: 0,
    armor: 2,
    armorType: "heavy",
    damageMin: 29,
    damageMax: 33,
    attackType: "normal",
    xpBounty: 120,
    goldBounty: 44,
    abilities: ["command_aura"],
    tags: ["murgul"],
  },

  // Sea creatures
  ntrs: {
    name: "Sea Turtle",
    level: 2,
    hp: 250,
    mana: 0,
    armor: 4,
    armorType: "heavy",
    damageMin: 6,
    damageMax: 10,
    attackType: "normal",
    xpBounty: 40,
    goldBounty: 14,
    abilities: ["spiked_shell"],
    tags: ["turtle"],
  },
  ntrh: {
    name: "Sea Turtle Hatchling",
    level: 1,
    hp: 220,
    mana: 0,
    armor: 0,
    armorType: "medium",
    damageMin: 13,
    damageMax: 15,
    attackType: "pierce",
    xpBounty: 25,
    goldBounty: 5,
    abilities: ["spiked_shell"],
    tags: ["turtle"],
  },
  nsc2: {
    name: "Spider Crab Limbripper",
    level: 3,
    hp: 400,
    mana: 0,
    armor: 1,
    armorType: "heavy",
    damageMin: 14,
    damageMax: 15,
    attackType: "normal",
    xpBounty: 60,
    goldBounty: 18,
    abilities: [],
    tags: ["crab"],
  },

  // Makrura / Murloc variants
  nmfs: {
    name: "Murloc Flesheater",
    level: 3,
    hp: 400,
    mana: 0,
    armor: 1,
    armorType: "heavy",
    damageMin: 13,
    damageMax: 14,
    attackType: "normal",
    xpBounty: 60,
    goldBounty: 18,
    abilities: ["cannibalize"],
    tags: ["murloc"],
  },

  // Mammoth
  nmam: {
    name: "Mammoth",
    level: 3,
    hp: 450,
    mana: 0,
    armor: 0,
    armorType: "heavy",
    damageMin: 14,
    damageMax: 16,
    attackType: "normal",
    xpBounty: 60,
    goldBounty: 18,
    abilities: [],
    tags: ["mammoth"],
  },

  // Granite Golem (boss variant)
  nggr: {
    name: "Granite Golem",
    level: 9,
    hp: 1500,
    mana: 600,
    armor: 5,
    armorType: "heavy",
    damageMin: 61,
    damageMax: 68,
    attackType: "chaos",
    xpBounty: 240,
    goldBounty: 92,
    abilities: ["hurl_boulder", "slam", "spell_immunity"],
    tags: ["golem"],
  },

  // Kobold variant
  nkot: {
    name: "Kobold Tunneler",
    level: 3,
    hp: 325,
    mana: 0,
    armor: 1,
    armorType: "medium",
    damageMin: 13,
    damageMax: 14,
    attackType: "normal",
    xpBounty: 60,
    goldBounty: 18,
    abilities: ["bash"],
    tags: ["kobold"],
  },

  // Red Dragon
  nrdr: {
    name: "Red Dragon",
    level: 6,
    hp: 950,
    mana: 0,
    armor: 2,
    armorType: "heavy",
    damageMin: 36,
    damageMax: 47,
    attackType: "pierce",
    xpBounty: 120,
    goldBounty: 48,
    abilities: [],
    tags: ["dragon"],
  },

  // Polar Furbolg variants
  nfpt: {
    name: "Polar Furbolg Tracker",
    level: 6,
    hp: 950,
    mana: 400,
    armor: 2,
    armorType: "heavy",
    damageMin: 29,
    damageMax: 33,
    attackType: "normal",
    xpBounty: 120,
    goldBounty: 44,
    abilities: ["slow"],
    tags: ["furbolg"],
  },
  nfps: {
    name: "Polar Furbolg Shaman",
    level: 4,
    hp: 550,
    mana: 300,
    armor: 0,
    armorType: "medium",
    damageMin: 25,
    damageMax: 32,
    attackType: "pierce",
    xpBounty: 80,
    goldBounty: 28,
    abilities: ["abolish_magic", "frost_armor"],
    tags: ["furbolg", "caster"],
  },
  npfl: {
    name: "Polar Furbolg",
    level: 2,
    hp: 300,
    mana: 0,
    armor: 0,
    armorType: "heavy",
    damageMin: 17,
    damageMax: 20,
    attackType: "pierce",
    xpBounty: 40,
    goldBounty: 14,
    abilities: [],
    tags: ["furbolg"],
  },

  // Fel demons
  nfgu: {
    name: "Fel Beast",
    level: 3,
    hp: 390,
    mana: 0,
    armor: 1,
    armorType: "heavy",
    damageMin: 14,
    damageMax: 15,
    attackType: "chaos",
    xpBounty: 60,
    goldBounty: 20,
    abilities: [],
    tags: ["demon"],
  },
  nfov: {
    name: "Fel Ravager",
    level: 7,
    hp: 950,
    mana: 300,
    armor: 4,
    armorType: "heavy",
    damageMin: 39,
    damageMax: 44,
    attackType: "chaos",
    xpBounty: 155,
    goldBounty: 60,
    abilities: ["black_arrow", "devour_magic"],
    tags: ["demon"],
  },
  ninf: {
    name: "Infernal",
    level: 8,
    hp: 1500,
    mana: 0,
    armor: 6,
    armorType: "heavy",
    damageMin: 49,
    damageMax: 60,
    attackType: "chaos",
    xpBounty: 200,
    goldBounty: 82,
    abilities: ["spell_immunity", "permanent_immolation", "resistant_skin"],
    tags: ["demon"],
  },

  // Stormreavers
  nsrh: {
    name: "Stormreaver Hermit",
    level: 3,
    hp: 340,
    mana: 200,
    armor: 2,
    armorType: "medium",
    damageMin: 21,
    damageMax: 25,
    attackType: "pierce",
    xpBounty: 60,
    goldBounty: 20,
    abilities: ["purge"],
    tags: ["stormreaver", "caster"],
  },
  nsra: {
    name: "Stormreaver Apprentice",
    level: 1,
    hp: 240,
    mana: 0,
    armor: 1,
    armorType: "medium",
    damageMin: 17,
    damageMax: 20,
    attackType: "pierce",
    xpBounty: 25,
    goldBounty: 8,
    abilities: [],
    tags: ["stormreaver"],
  },
  nsrv: {
    name: "Revenant of the Seas",
    level: 5,
    hp: 900,
    mana: 0,
    armor: 2,
    armorType: "heavy",
    damageMin: 24,
    damageMax: 27,
    attackType: "normal",
    xpBounty: 100,
    goldBounty: 38,
    abilities: [],
    tags: ["revenant"],
  },

  // Tuskarr variants
  ntkt: {
    name: "Tuskarr Trapper",
    level: 4,
    hp: 475,
    mana: 0,
    armor: 1,
    armorType: "medium",
    damageMin: 28,
    damageMax: 34,
    attackType: "pierce",
    xpBounty: 80,
    goldBounty: 28,
    abilities: ["ensnare"],
    tags: ["tuskarr"],
  },
  ntks: {
    name: "Tuskarr Sorcerer",
    level: 5,
    hp: 475,
    mana: 300,
    armor: 0,
    armorType: "medium",
    damageMin: 34,
    damageMax: 40,
    attackType: "pierce",
    xpBounty: 100,
    goldBounty: 38,
    abilities: ["inner_fire"],
    tags: ["tuskarr", "caster"],
  },

  // Sludge
  nslf: {
    name: "Sludge Flinger",
    level: 3,
    hp: 340,
    mana: 300,
    armor: 0,
    armorType: "medium",
    damageMin: 23,
    damageMax: 27,
    attackType: "pierce",
    xpBounty: 60,
    goldBounty: 20,
    abilities: ["slow"],
    tags: ["sludge", "caster"],
  },

  // Wildkin variant
  nowe: {
    name: "Enraged Wildkin",
    level: 6,
    hp: 950,
    mana: 0,
    armor: 3,
    armorType: "heavy",
    damageMin: 29,
    damageMax: 33,
    attackType: "normal",
    xpBounty: 120,
    goldBounty: 44,
    abilities: ["war_stomp", "bash"],
    tags: ["wildkin"],
  },

  // Arachnathid
  nanw: {
    name: "Warrior Arachnathid",
    level: 3,
    hp: 375,
    mana: 0,
    armor: 2,
    armorType: "heavy",
    damageMin: 14,
    damageMax: 15,
    attackType: "normal",
    xpBounty: 60,
    goldBounty: 18,
    abilities: [],
    tags: ["arachnathid"],
  },
  nano: {
    name: "Overlord Arachnathid",
    level: 5,
    hp: 750,
    mana: 0,
    armor: 2,
    armorType: "heavy",
    damageMin: 24,
    damageMax: 27,
    attackType: "normal",
    xpBounty: 100,
    goldBounty: 38,
    abilities: ["command_aura"],
    tags: ["arachnathid"],
  },
  nanc: {
    name: "Crystal Arachnathid",
    level: 1,
    hp: 200,
    mana: 0,
    armor: 2,
    armorType: "heavy",
    damageMin: 10,
    damageMax: 11,
    attackType: "normal",
    xpBounty: 25,
    goldBounty: 5,
    abilities: [],
    tags: ["arachnathid"],
  },
  nanb: {
    name: "Barbed Arachnathid",
    level: 1,
    hp: 200,
    mana: 0,
    armor: 1,
    armorType: "medium",
    damageMin: 13,
    damageMax: 15,
    attackType: "pierce",
    xpBounty: 25,
    goldBounty: 5,
    abilities: ["envenomed_weapons"],
    tags: ["arachnathid"],
  },

  // Nerubian Webspinner
  nnwl: {
    name: "Nerubian Webspinner",
    level: 3,
    hp: 240,
    mana: 300,
    armor: 0,
    armorType: "heavy",
    damageMin: 21,
    damageMax: 25,
    attackType: "pierce",
    xpBounty: 60,
    goldBounty: 20,
    abilities: ["web", "raise_dead"],
    tags: ["nerubian", "caster"],
  },

  // Assassin
  nass: {
    name: "Assassin",
    level: 4,
    hp: 450,
    mana: 0,
    armor: 1,
    armorType: "medium",
    damageMin: 25,
    damageMax: 30,
    attackType: "pierce",
    xpBounty: 80,
    goldBounty: 13,
    abilities: ["hide", "envenomed_weapons"],
    tags: ["assassin"],
  },

  // Polar Bears
  nplb: {
    name: "Polar Bear",
    level: 4,
    hp: 475,
    mana: 0,
    armor: 2,
    armorType: "heavy",
    damageMin: 21,
    damageMax: 25,
    attackType: "normal",
    xpBounty: 80,
    goldBounty: 28,
    abilities: [],
    tags: ["bear"],
  },
  nplg: {
    name: "Giant Polar Bear",
    level: 6,
    hp: 900,
    mana: 0,
    armor: 3,
    armorType: "heavy",
    damageMin: 34,
    damageMax: 38,
    attackType: "normal",
    xpBounty: 120,
    goldBounty: 44,
    abilities: [],
    tags: ["bear"],
  },

  // Sea Giants
  nsgn: {
    name: "Sea Giant",
    level: 3,
    hp: 350,
    mana: 0,
    armor: 0,
    armorType: "heavy",
    damageMin: 12,
    damageMax: 13,
    attackType: "normal",
    xpBounty: 60,
    goldBounty: 18,
    abilities: ["pulverize"],
    tags: ["giant"],
  },
  nsgh: {
    name: "Sea Giant Hunter",
    level: 5,
    hp: 750,
    mana: 0,
    armor: 0,
    armorType: "heavy",
    damageMin: 20,
    damageMax: 23,
    attackType: "normal",
    xpBounty: 100,
    goldBounty: 38,
    abilities: ["pulverize", "ensnare"],
    tags: ["giant"],
  },

  // Specials
  nsel: {
    name: "Poison Treant",
    level: 3,
    hp: 290,
    mana: 300,
    armor: 0,
    armorType: "heavy",
    damageMin: 18,
    damageMax: 21,
    attackType: "normal",
    xpBounty: 60,
    goldBounty: 18,
    abilities: ["entangling_roots", "envenomed_weapons"],
    tags: ["treant"],
  },
  narg: {
    name: "Battle Golem",
    level: 3,
    hp: 500,
    mana: 0,
    armor: 0,
    armorType: "medium",
    damageMin: 11,
    damageMax: 12,
    attackType: "normal",
    xpBounty: 60,
    goldBounty: 9,
    abilities: ["spell_immunity"],
    tags: ["golem"],
  },
  nhdc: {
    name: "Deceiver",
    level: 3,
    hp: 300,
    mana: 300,
    armor: 0,
    armorType: "heavy",
    damageMin: 23,
    damageMax: 27,
    attackType: "pierce",
    xpBounty: 60,
    goldBounty: 9,
    abilities: ["curse"],
    tags: ["caster"],
  },
  nrvi: {
    name: "Ice Revenant",
    level: 8,
    hp: 1100,
    mana: 500,
    armor: 4,
    armorType: "heavy",
    damageMin: 49,
    damageMax: 55,
    attackType: "chaos",
    xpBounty: 200,
    goldBounty: 76,
    abilities: ["frost_nova", "vampiric_aura"],
    tags: ["undead", "revenant"],
  },
  nvdg: {
    name: "Greater Voidwalker",
    level: 6,
    hp: 750,
    mana: 400,
    armor: 0,
    armorType: "heavy",
    damageMin: 36,
    damageMax: 43,
    attackType: "pierce",
    xpBounty: 120,
    goldBounty: 44,
    abilities: ["chain_lightning", "frost_armor"],
    tags: ["void", "caster"],
  },
};
